// Culinary glossary — injected into the LLM translation prompt as
// a "use these exact translations" hint. Fixes the most common machine
// translation mistakes for food/cooking vocabulary.
//
// Keep each language list lean (~50 terms) so the prompt doesn't balloon.

export const GLOSSARY = {
  vi: {
    // Cooking verbs
    "sauté": "xào",
    "stir-fry": "xào",
    "stir fry": "xào",
    "pan-fry": "áp chảo",
    "deep-fry": "chiên ngập dầu",
    "fry": "chiên",
    "simmer": "ninh nhỏ lửa",
    "braise": "om",
    "boil": "luộc",
    "parboil": "trần qua",
    "blanch": "trần",
    "steam": "hấp",
    "roast": "nướng",
    "bake": "nướng lò",
    "grill": "nướng vỉ",
    "broil": "nướng lửa trên",
    "poach": "chần",
    "sear": "áp chảo cháy cạnh",
    "brown": "chiên vàng",
    "caramelize": "thắng đường",
    "marinate": "ướp",
    "season": "nêm gia vị",
    "whisk": "đánh đều",
    "beat": "đánh bông",
    "whip": "đánh bông",
    "fold in": "trộn nhẹ",
    "knead": "nhào bột",
    "garnish": "trang trí",
    "drizzle": "rưới",
    "toss": "trộn đều",
    "reduce": "đun cô đặc",
    "deglaze": "tráng chảo",
    "baste": "phết nước",
    // Cutting
    "dice": "cắt hạt lựu",
    "mince": "băm nhỏ",
    "chop": "xắt nhỏ",
    "slice": "thái lát",
    "shred": "bào sợi",
    "julienne": "thái sợi",
    "grate": "nạo",
    "peel": "gọt vỏ",
    "de-vein": "rút chỉ đen (tôm)",
    // Common ingredients that machines mis-translate
    "ground beef": "thịt bò xay",
    "ground pork": "thịt heo xay",
    "beef slices": "thịt bò thái lát",
    "beef strips": "thịt bò thái sợi",
    "scallion": "hành lá",
    "green onion": "hành lá",
    "spring onion": "hành lá",
    "cilantro": "ngò rí",
    "coriander": "ngò rí",
    "bell pepper": "ớt chuông",
    "chili": "ớt",
    "fish sauce": "nước mắm",
    "soy sauce": "nước tương",
    "oyster sauce": "dầu hào",
    "rice vinegar": "giấm gạo",
    "sesame oil": "dầu mè",
    "star anise": "hoa hồi",
    "lemongrass": "sả",
    "galangal": "riềng",
    "kaffir lime leaves": "lá chanh",
    "shrimp paste": "mắm tôm",
    "rice noodles": "bún/phở",
    "glass noodles": "miến",
    "tofu": "đậu hũ",
    "bean sprouts": "giá đỗ",
  },

  es: {
    // Cooking verbs (Castilian)
    "sauté": "saltear",
    "stir-fry": "saltear al wok",
    "pan-fry": "freír en sartén",
    "deep-fry": "freír en abundante aceite",
    "simmer": "cocer a fuego lento",
    "braise": "estofar",
    "boil": "hervir",
    "blanch": "escaldar",
    "steam": "cocer al vapor",
    "roast": "asar",
    "bake": "hornear",
    "grill": "asar a la parrilla",
    "broil": "gratinar",
    "poach": "escalfar",
    "sear": "sellar",
    "brown": "dorar",
    "caramelize": "caramelizar",
    "marinate": "marinar",
    "season": "sazonar",
    "whisk": "batir",
    "whip": "montar",
    "fold in": "mezclar con movimientos envolventes",
    "knead": "amasar",
    "garnish": "decorar",
    "drizzle": "rociar",
    "toss": "mezclar",
    "reduce": "reducir",
    "deglaze": "desglasar",
    // Cutting
    "dice": "cortar en dados",
    "mince": "picar fino",
    "chop": "picar",
    "slice": "cortar en rodajas",
    "shred": "desmenuzar",
    "julienne": "cortar en juliana",
    "grate": "rallar",
    "peel": "pelar",
    // Ingredients
    "ground beef": "carne picada de ternera",
    "beef slices": "lonchas de ternera",
    "scallion": "cebolleta",
    "green onion": "cebolleta",
    "cilantro": "cilantro",
    "bell pepper": "pimiento",
    "chili": "guindilla",
    "fish sauce": "salsa de pescado",
    "soy sauce": "salsa de soja",
    "oyster sauce": "salsa de ostras",
    "rice vinegar": "vinagre de arroz",
    "sesame oil": "aceite de sésamo",
    "lemongrass": "hierba limón",
    "rice noodles": "fideos de arroz",
    "bean sprouts": "brotes de soja",
    "tofu": "tofu",
  },

  zh: {
    // Cooking verbs (Simplified Chinese)
    "sauté": "炒",
    "stir-fry": "爆炒",
    "pan-fry": "煎",
    "deep-fry": "油炸",
    "simmer": "慢炖",
    "braise": "红烧",
    "boil": "煮",
    "blanch": "焯水",
    "steam": "蒸",
    "roast": "烤",
    "bake": "烘焙",
    "grill": "炭烤",
    "poach": "水煮",
    "sear": "煎封",
    "brown": "煎至金黄",
    "caramelize": "焦糖化",
    "marinate": "腌制",
    "season": "调味",
    "whisk": "搅打",
    "whip": "打发",
    "knead": "揉面",
    "garnish": "装饰",
    "toss": "翻拌",
    "reduce": "收汁",
    // Cutting
    "dice": "切丁",
    "mince": "剁碎",
    "chop": "切碎",
    "slice": "切片",
    "shred": "切丝",
    "julienne": "切细丝",
    "grate": "磨碎",
    "peel": "去皮",
    // Ingredients
    "ground beef": "牛肉末",
    "beef slices": "牛肉片",
    "scallion": "葱",
    "green onion": "葱",
    "cilantro": "香菜",
    "bell pepper": "彩椒",
    "chili": "辣椒",
    "fish sauce": "鱼露",
    "soy sauce": "酱油",
    "oyster sauce": "蚝油",
    "rice vinegar": "米醋",
    "sesame oil": "麻油",
    "star anise": "八角",
    "lemongrass": "香茅",
    "galangal": "南姜",
    "shrimp paste": "虾酱",
    "rice noodles": "米粉",
    "bean sprouts": "豆芽",
    "tofu": "豆腐",
  },
};

/**
 * Format the glossary as a bullet list that can be inlined into an LLM prompt.
 * Only includes terms for the requested target language.
 */
export function glossaryPromptFor(target) {
  const dict = GLOSSARY[target];
  if (!dict) return "";
  const lines = Object.entries(dict)
    .map(([en, tr]) => `  "${en}" → "${tr}"`)
    .join("\n");
  return lines;
}
